export type WizardConfig = {
  name: string;
  modules: string[];
  auth: string;
  database: string;
  ai?: string;
  queue: string;
  loginLayout: string;
  style: string;
  deploy: string;
};

export const MODULES = [
  { id: "auth", label: "Authentication & users", default: true },
  { id: "payments", label: "Payments (Stripe)", default: true },
  { id: "ai", label: "AI Workflows", default: false },
  { id: "teams", label: "Teams & organizations", default: true },
  { id: "blog", label: "Blog & CMS", default: false },
  { id: "helpdesk", label: "Helpdesk & support", default: false },
  { id: "affiliates", label: "Affiliate program", default: false },
  { id: "crm", label: "CRM", default: false },
] as const;

export const AUTH_PROVIDERS = [
  { id: "authjs", label: "Auth.js v5", hint: "recommended — self-hosted, any DB" },
  { id: "clerk", label: "Clerk", hint: "managed — fastest setup" },
  { id: "better-auth", label: "Better-Auth", hint: "modern self-hosted" },
  { id: "supabase", label: "Supabase Auth", hint: "integrated with Supabase" },
] as const;

export const DATABASES = [
  { id: "neon", label: "Neon Postgres", hint: "recommended — serverless" },
  { id: "supabase", label: "Supabase Postgres" },
  { id: "postgres", label: "Self-hosted Postgres" },
  { id: "planetscale", label: "PlanetScale MySQL" },
] as const;

export const AI_PROVIDERS = [
  { id: "openai", label: "OpenAI" },
  { id: "anthropic", label: "Anthropic" },
  { id: "groq", label: "Groq" },
  { id: "google", label: "Google Gemini" },
  { id: "multi", label: "Multi-provider" },
] as const;

export const QUEUES = [
  { id: "inngest", label: "Inngest", hint: "recommended for Vercel" },
  { id: "bullmq", label: "BullMQ + Redis", hint: "self-hosted VPS" },
  { id: "qstash", label: "Upstash QStash", hint: "minimal cron" },
] as const;

export const LOGIN_LAYOUTS = [
  { id: "centered-card", label: "Centered card" },
  { id: "split-screen", label: "Split screen" },
  { id: "illustration", label: "Illustration" },
  { id: "minimal", label: "Minimal" },
  { id: "fullscreen", label: "Fullscreen image" },
] as const;

export const STYLE_PRESETS = [
  { id: "rounded", label: "Rounded", hint: "Notion / Linear" },
  { id: "sharp", label: "Sharp", hint: "Figma / Stripe" },
  { id: "outline", label: "Outline", hint: "Vercel / Supabase" },
  { id: "gradient", label: "Gradient", hint: "Clerk / Resend" },
] as const;

export const DEPLOY_TARGETS = [
  { id: "vercel", label: "Vercel", hint: "recommended — zero config" },
  { id: "railway", label: "Railway" },
  { id: "fly", label: "Fly.io" },
  { id: "render", label: "Render" },
  { id: "vps", label: "Self-hosted VPS" },
] as const;

export function buildNpxCommand(config: WizardConfig): string {
  const parts = [
    "npx create-foundry@latest",
    `--name ${config.name}`,
    `--auth ${config.auth}`,
    `--db ${config.database}`,
  ];
  if (config.modules.includes("ai") && config.ai) {
    parts.push(`--ai ${config.ai}`);
  }
  parts.push(
    `--queue ${config.queue}`,
    `--login-layout ${config.loginLayout}`,
    `--style ${config.style}`,
    `--deploy ${config.deploy}`,
    `--modules ${config.modules.join(",")}`
  );
  return parts.join(" \\\n  ");
}

export function generateEnvExample(config: WizardConfig): string {
  const lines: string[] = [
    "# Foundry — Environment Variables",
    `# Generated for: ${config.name}`,
    "",
    "# App",
    "NEXT_PUBLIC_APP_URL=http://localhost:3000",
    "",
  ];

  if (config.modules.includes("auth")) {
    lines.push(
      "# Auth (Auth.js)",
      "AUTH_SECRET=generate-with-openssl-rand-base64-32",
      "GOOGLE_CLIENT_ID=",
      "GOOGLE_CLIENT_SECRET=",
      "GITHUB_CLIENT_ID=",
      "GITHUB_CLIENT_SECRET=",
      ""
    );
  }

  lines.push("# Database", "DATABASE_URL=postgresql://user:pass@host/db?sslmode=require", "");

  if (config.modules.includes("payments")) {
    lines.push(
      "# Stripe",
      "STRIPE_SECRET_KEY=sk_test_...",
      "STRIPE_WEBHOOK_SECRET=whsec_...",
      "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_...",
      ""
    );
  }

  if (config.modules.includes("ai")) {
    lines.push(
      `# AI (${config.ai ?? "openai"})`,
      config.ai === "anthropic" ? "ANTHROPIC_API_KEY=" : "OPENAI_API_KEY=",
      ""
    );
  }

  lines.push("# Email", "RESEND_API_KEY=re_...", "");

  if (config.queue === "inngest") {
    lines.push("# Inngest", "INNGEST_EVENT_KEY=", "INNGEST_SIGNING_KEY=", "");
  }

  return lines.join("\n");
}

export function generatePlatformConfig(config: WizardConfig): string {
  const modulesObj = Object.fromEntries(
    MODULES.map((m) => [m.id, config.modules.includes(m.id)])
  );

  return `// platform.config.ts — generated by create-foundry
export const platform = {
  app: {
    name: '${config.name}',
    url: process.env.NEXT_PUBLIC_APP_URL!,
    supportEmail: 'support@${config.name.toLowerCase().replace(/\s+/g, "")}.com',
  },
  modules: ${JSON.stringify(modulesObj, null, 4).replace(/"([^"]+)":/g, "$1:")},
  auth: { provider: '${config.auth}' },
  database: { provider: '${config.database}' },
  ai: { provider: '${config.ai ?? "openai"}' },
  queues: { provider: '${config.queue}' },
  ui: {
    loginLayout: '${config.loginLayout}',
    stylePreset: '${config.style}',
  },
  deployment: { target: '${config.deploy}' },
} as const;
`;
}
